#!/bin/bash
# ═══════════════════════════════════════════
# STARDANCE PORTFOLIO — AI-Built Demo
# Generated by AI Autonomous Task System
# ═══════════════════════════════════════════

PROJECT_DIR="portfolio-demo"
mkdir -p "$PROJECT_DIR"/{css,js,img}

# ─── index.html ───
cat > "$PROJECT_DIR/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stardance Portfolio — AI Autonomous Task System</title>
  <link rel="stylesheet" href="css/style.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&family=Rajdhani:wght@300;400;500;600;700&family=Share+Tech+Mono&display=swap" rel="stylesheet">
</head>
<body>
  <canvas id="particles"></canvas>

  <nav class="navbar">
    <div class="nav-brand">
      <span class="logo-icon">🤖</span>
      <span class="logo-text">STARDANCE // REMOTE</span>
    </div>
    <div class="nav-links">
      <a href="#hero" class="nav-link">HOME</a>
      <a href="#about" class="nav-link">ABOUT</a>
      <a href="#projects" class="nav-link">PROJECTS</a>
      <a href="#skills" class="nav-link">SKILLS</a>
      <a href="#contact" class="nav-link btn-nav">CONTACT</a>
    </div>
    <div class="hamburger" id="hamburger">
      <span></span><span></span><span></span>
    </div>
  </nav>

  <section id="hero" class="hero">
    <div class="hero-content">
      <p class="hero-tag">STARDANCE CHALLENGE // 2026</p>
      <h1>AI AUTONOMOUS<br><span class="gradient-text">TASK SYSTEM</span></h1>
      <p class="hero-sub">An autonomous AI developer that plans, executes, and self-corrects on software projects — running fully offline in school mode.</p>
      <div class="hero-actions">
        <a href="#projects" class="btn-primary">VIEW PROJECTS</a>
        <a href="#contact" class="btn-secondary">GET IN TOUCH</a>
      </div>
      <div class="hero-stats">
        <div class="stat">
          <span class="stat-num" data-count="3">0</span>
          <span class="stat-label">PROJECTS BUILT</span>
        </div>
        <div class="stat">
          <span class="stat-num" data-count="16">0</span>
          <span class="stat-label">TASKS EXECUTED</span>
        </div>
        <div class="stat">
          <span class="stat-num" data-count="100">0</span>
          <span class="stat-label">AUTONOMY %</span>
        </div>
      </div>
    </div>
    <div class="hero-corner tl"></div>
    <div class="hero-corner tr"></div>
    <div class="hero-corner bl"></div>
    <div class="hero-corner br"></div>
  </section>

  <section id="about" class="section">
    <div class="section-header">
      <span class="section-tag">// ABOUT</span>
      <h2>Who Built This</h2>
    </div>
    <div class="about-grid">
      <div class="about-text">
        <p>This project was built by an <strong>AI Autonomous Task Agent</strong> — a system that takes a project description, uses AI (GPT-4 / Claude) to generate a complete implementation plan, and executes it autonomously through shell commands.</p>
        <p>The agent runs in <strong>School Mode</strong> — tasks execute in the background, fully offline, even when the developer is away. It self-corrects failures and sends progress notifications every 20 minutes.</p>
        <p class="highlight">Welcome to the future of software development. <br>You describe it. The AI builds it. You review it.</p>
      </div>
      <div class="about-features">
        <div class="feature-card">
          <div class="feature-icon">🤖</div>
          <h3>AI Planning</h3>
          <p>Uses GPT-4o-mini or Claude to generate complete task plans from project descriptions</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">⚡</div>
          <h3>Autonomous Execution</h3>
          <p>Runs shell commands automatically — creates files, installs dependencies, writes code</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">🏫</div>
          <h3>School Mode</h3>
          <p>Tasks run in background while you're away. Works fully offline. No internet needed.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">🔧</div>
          <h3>Self-Correction</h3>
          <p>Failed tasks are automatically retried. The agent learns and adapts.</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">📊</div>
          <h3>Real-Time Dashboard</h3>
          <p>Jarvis HUD-style interface with live WebSocket progress tracking</p>
        </div>
        <div class="feature-card">
          <div class="feature-icon">🔔</div>
          <h3>Smart Notifications</h3>
          <p>Progress reports every 20 minutes. Browser and system notifications.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="projects" class="section dark-section">
    <div class="section-header">
      <span class="section-tag">// PROJECTS</span>
      <h2>What Was Built</h2>
    </div>
    <div class="projects-grid">
      <div class="project-card">
        <div class="project-card-glow"></div>
        <div class="project-icon">🤖</div>
        <div class="project-number">01</div>
        <h3>AI Autonomous Task System</h3>
        <p class="project-tag">AI // SYSTEMS // AUTOMATION</p>
        <p>A complete autonomous AI developer that plans projects, executes shell commands, self-corrects failures, and runs in school mode offline. Built with Node.js, Express, WebSocket, and AI API integration.</p>
        <div class="project-tech">
          <span class="tech-badge">Node.js</span>
          <span class="tech-badge">Express</span>
          <span class="tech-badge">WebSocket</span>
          <span class="tech-badge">GPT-4</span>
          <span class="tech-badge">Claude</span>
        </div>
        <div class="project-stats">
          <div class="proj-stat"><span class="proj-num">16</span><span class="proj-label">Tasks Run</span></div>
          <div class="proj-stat"><span class="proj-num">100%</span><span class="proj-label">Success Rate</span></div>
          <div class="proj-stat"><span class="proj-num">3h</span><span class="proj-label">Built In</span></div>
        </div>
        <a href="https://github.com/kiyanshsaini604-cmyk/stardance-remote" target="_blank" class="project-link">VIEW ON GITHUB →</a>
      </div>

      <div class="project-card">
        <div class="project-card-glow"></div>
        <div class="project-icon">🌐</div>
        <div class="project-number">02</div>
        <h3>Stardance Remote Control</h3>
        <p class="project-tag">SYSTEMS // DASHBOARD // REMOTE</p>
        <p>A remote-controlled development dashboard that lets you manage coding tasks from any device. Features Jarvis HUD UI, real-time WebSocket updates, school mode auto-execution, and progress notifications.</p>
        <div class="project-tech">
          <span class="tech-badge">HTML/CSS</span>
          <span class="tech-badge">JavaScript</span>
          <span class="tech-badge">WebSocket</span>
          <span class="tech-badge">Node.js</span>
        </div>
        <div class="project-stats">
          <div class="proj-stat"><span class="proj-num">24/7</span><span class="proj-label">Accessible</span></div>
          <div class="proj-stat"><span class="proj-num">30s</span><span class="proj-label">Check Interval</span></div>
          <div class="proj-stat"><span class="proj-num">20min</span><span class="proj-label">Notify Rate</span></div>
        </div>
        <a href="https://github.com/kiyanshsaini604-cmyk/stardance-remote" target="_blank" class="project-link">VIEW ON GITHUB →</a>
      </div>

      <div class="project-card">
        <div class="project-card-glow"></div>
        <div class="project-icon">📝</div>
        <div class="project-number">03</div>
        <h3>Devlog Generator</h3>
        <p class="project-tag">TOOLS // AUTOMATION // STARDANCE</p>
        <p>One-click devlog generation for Stardance challenge submissions. Automatically compiles session activity, task completions, and progress into formatted Markdown ready to paste on the Stardance dashboard.</p>
        <div class="project-tech">
          <span class="tech-badge">Markdown</span>
          <span class="tech-badge">Node.js</span>
          <span class="tech-badge">Automation</span>
        </div>
        <div class="project-stats">
          <div class="proj-stat"><span class="proj-num">1-click</span><span class="proj-label">Generate</span></div>
          <div class="proj-stat"><span class="proj-num">Auto</span><span class="proj-label">Formatting</span></div>
        </div>
        <a href="https://github.com/kiyanshsaini604-cmyk/stardance-remote" target="_blank" class="project-link">VIEW ON GITHUB →</a>
      </div>
    </div>
  </section>

  <section id="skills" class="section">
    <div class="section-header">
      <span class="section-tag">// SKILLS</span>
      <h2>Technical Proficiency</h2>
    </div>
    <div class="skills-grid">
      <div class="skill-item">
        <div class="skill-header">
          <span>Node.js / Express</span>
          <span class="skill-val">95%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="95"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>JavaScript / TypeScript</span>
          <span class="skill-val">90%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="90"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>AI / LLM Integration</span>
          <span class="skill-val">85%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="85"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>HTML / CSS / UI Design</span>
          <span class="skill-val">88%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="88"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>WebSocket / Real-Time</span>
          <span class="skill-val">82%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="82"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>Shell Scripting / DevOps</span>
          <span class="skill-val">78%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="78"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>Git / GitHub</span>
          <span class="skill-val">80%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="80"></div></div>
      </div>
      <div class="skill-item">
        <div class="skill-header">
          <span>System Architecture</span>
          <span class="skill-val">85%</span>
        </div>
        <div class="skill-bar"><div class="skill-fill" data-width="85"></div></div>
      </div>
    </div>
  </section>

  <section id="contact" class="section dark-section">
    <div class="section-header">
      <span class="section-tag">// CONTACT</span>
      <h2>Get In Touch</h2>
    </div>
    <div class="contact-container">
      <div class="contact-info">
        <div class="contact-item">
          <span class="contact-icon">📧</span>
          <div>
            <span class="contact-label">Email</span>
            <span class="contact-value">dev@stardance.hackclub.com</span>
          </div>
        </div>
        <div class="contact-item">
          <span class="contact-icon">🐙</span>
          <div>
            <span class="contact-label">GitHub</span>
            <span class="contact-value">kiyanshsaini604-cmyk</span>
          </div>
        </div>
        <div class="contact-item">
          <span class="contact-icon">🏆</span>
          <div>
            <span class="contact-label">Stardance</span>
            <span class="contact-value">Active Participant</span>
          </div>
        </div>
        <p class="contact-note">Built during the Stardance Challenge — Summer 2026<br>Partnered with NASA & AMD</p>
      </div>
      <form class="contact-form" id="contact-form" onsubmit="return handleContact(event)">
        <div class="form-group">
          <input type="text" placeholder="Your Name" required>
        </div>
        <div class="form-group">
          <input type="email" placeholder="Your Email" required>
        </div>
        <div class="form-group">
          <textarea placeholder="Your Message" rows="4" required></textarea>
        </div>
        <button type="submit" class="btn-primary contact-btn">SEND MESSAGE ⟫</button>
      </form>
    </div>
  </section>

  <footer class="footer">
    <div class="footer-content">
      <div class="footer-brand">
        <span class="logo-icon">🤖</span>
        <span class="logo-text">STARDANCE // REMOTE</span>
      </div>
      <p class="footer-text">AI Autonomous Task System — Built for the Stardance Challenge 2026</p>
      <div class="footer-links">
        <a href="https://stardance.hackclub.com" target="_blank">Stardance</a>
        <a href="https://hackclub.com" target="_blank">Hack Club</a>
        <a href="https://github.com/kiyanshsaini604-cmyk/stardance-remote" target="_blank">GitHub</a>
      </div>
      <p class="footer-copy">© 2026 — Made with 🤖 by the AI Agent</p>
    </div>
    <div class="footer-corner tl"></div>
    <div class="footer-corner tr"></div>
    <div class="footer-corner bl"></div>
    <div class="footer-corner br"></div>
  </footer>

  <script src="js/app.js"></script>
</body>
</html>
HTMLEOF

# ─── style.css ───
cat > "$PROJECT_DIR/css/style.css" << 'CSSEOF'
/* ═══════════════════════════════════════════
   STARDANCE PORTFOLIO — STYLES
   Dark premium theme with cyan accents
   ═══════════════════════════════════════════ */

@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&family=Rajdhani:wght@300;400;500;600;700&family=Share+Tech+Mono&display=swap');

:root {
  --bg: #020a12;
  --bg-alt: #061220;
  --bg-card: rgba(6, 25, 45, 0.85);
  --cyan: #00d4ff;
  --cyan-bright: #00f0ff;
  --cyan-dim: #0088aa;
  --text: #c8e6f8;
  --text-bright: #e0f4ff;
  --text-muted: rgba(140, 180, 210, 0.6);
  --font-display: 'Orbitron', monospace;
  --font-ui: 'Rajdhani', sans-serif;
  --font-mono: 'Share Tech Mono', monospace;
  --radius: 2px;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

html { scroll-behavior: smooth; }

body {
  font-family: var(--font-ui);
  background: var(--bg);
  color: var(--text);
  overflow-x: hidden;
  line-height: 1.5;
}

/* ─── Particle Canvas ─── */
#particles {
  position: fixed;
  inset: 0;
  z-index: 0;
  pointer-events: none;
}

/* ─── Utility ─── */
section { position: relative; z-index: 1; }

.gradient-text {
  background: linear-gradient(135deg, var(--cyan-dim), var(--cyan-bright));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

/* ─── Navbar ─── */
.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 2rem;
  background: rgba(2, 10, 18, 0.85);
  backdrop-filter: blur(10px);
  border-bottom: 1px solid rgba(0, 180, 255, 0.1);
}

.nav-brand {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.logo-icon { font-size: 1.3rem; }

.logo-text {
  font-family: var(--font-display);
  font-size: 0.75rem;
  font-weight: 700;
  color: var(--cyan);
  letter-spacing: 0.15em;
  text-transform: uppercase;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: 1.5rem;
}

.nav-link {
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: var(--text-muted);
  text-decoration: none;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  transition: color 0.3s;
  padding: 0.3rem 0;
  border-bottom: 1px solid transparent;
}

.nav-link:hover {
  color: var(--cyan);
  border-bottom-color: var(--cyan);
}

.btn-nav {
  padding: 0.4rem 1rem;
  background: rgba(0,180,255,0.1);
  border: 1px solid rgba(0,180,255,0.2);
  color: var(--cyan);
}

.btn-nav:hover {
  background: rgba(0,180,255,0.2);
  border-color: var(--cyan);
}

.hamburger {
  display: none;
  flex-direction: column;
  gap: 4px;
  cursor: pointer;
}

.hamburger span {
  width: 24px;
  height: 2px;
  background: var(--cyan);
}

/* ─── Hero ─── */
.hero {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 6rem 2rem 4rem;
  position: relative;
}

.hero-content {
  text-align: center;
  max-width: 800px;
}

.hero-tag {
  font-family: var(--font-mono);
  font-size: 0.75rem;
  color: var(--text-muted);
  letter-spacing: 0.2em;
  margin-bottom: 1rem;
}

.hero h1 {
  font-family: var(--font-display);
  font-size: 4rem;
  font-weight: 800;
  color: var(--text-bright);
  line-height: 1.1;
  margin-bottom: 1.5rem;
  letter-spacing: 0.05em;
}

.hero-sub {
  font-size: 1.1rem;
  color: var(--text-muted);
  max-width: 600px;
  margin: 0 auto 2rem;
  line-height: 1.6;
}

.hero-actions {
  display: flex;
  gap: 1rem;
  justify-content: center;
  margin-bottom: 3rem;
}

.btn-primary {
  padding: 0.8rem 1.6rem;
  background: linear-gradient(135deg, rgba(0,180,255,0.2), rgba(0,180,255,0.05));
  color: var(--cyan);
  border: 1px solid var(--cyan);
  text-decoration: none;
  font-family: var(--font-ui);
  font-weight: 600;
  font-size: 0.85rem;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  transition: all 0.3s;
  clip-path: polygon(6px 0, 100% 0, 100% calc(100% - 6px), calc(100% - 6px) 100%, 0 100%, 0 6px);
}

.btn-primary:hover {
  background: linear-gradient(135deg, rgba(0,180,255,0.4), rgba(0,180,255,0.1));
  box-shadow: 0 0 20px rgba(0,180,255,0.3);
  transform: translateY(-2px);
}

.btn-secondary {
  padding: 0.8rem 1.6rem;
  background: transparent;
  color: var(--text-muted);
  border: 1px solid rgba(0,180,255,0.15);
  text-decoration: none;
  font-family: var(--font-ui);
  font-weight: 600;
  font-size: 0.85rem;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  transition: all 0.3s;
  clip-path: polygon(6px 0, 100% 0, 100% calc(100% - 6px), calc(100% - 6px) 100%, 0 100%, 0 6px);
}

.btn-secondary:hover {
  color: var(--cyan);
  border-color: var(--cyan);
}

.hero-stats {
  display: flex;
  justify-content: center;
  gap: 3rem;
}

.hero-stat {
  text-align: center;
}

.stat-num {
  display: block;
  font-family: var(--font-display);
  font-size: 2.5rem;
  font-weight: 700;
  color: var(--cyan-bright);
  text-shadow: 0 0 15px rgba(0,210,255,0.5);
}

.stat-label {
  font-family: var(--font-mono);
  font-size: 0.6rem;
  color: var(--text-muted);
  letter-spacing: 0.15em;
  margin-top: 0.3rem;
}

/* ─── Corners ─── */
.hero-corner {
  position: absolute;
  width: 40px;
  height: 40px;
  border-color: var(--cyan);
  opacity: 0.3;
}

.hero-corner.tl { top: 1rem; left: 1rem; border-top: 2px solid; border-left: 2px solid; }
.hero-corner.tr { top: 1rem; right: 1rem; border-top: 2px solid; border-right: 2px solid; }
.hero-corner.bl { bottom: 1rem; left: 1rem; border-bottom: 2px solid; border-left: 2px solid; }
.hero-corner.br { bottom: 1rem; right: 1rem; border-bottom: 2px solid; border-right: 2px solid; }

/* ─── Sections ─── */
.section {
  padding: 5rem 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.dark-section {
  background: var(--bg-alt);
}

.section-header {
  text-align: center;
  margin-bottom: 3rem;
}

.section-tag {
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: var(--cyan);
  letter-spacing: 0.2em;
  margin-bottom: 0.5rem;
}

.section-header h2 {
  font-family: var(--font-display);
  font-size: 2rem;
  font-weight: 600;
  color: var(--text-bright);
  letter-spacing: 0.1em;
}

/* ─── About ─── */
.about-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  align-items: start;
}

.about-text p {
  color: var(--text-muted);
  font-size: 1.05rem;
  margin-bottom: 1rem;
  line-height: 1.7;
}

.highlight {
  color: var(--cyan);
  font-style: italic;
  border-left: 2px solid var(--cyan);
  padding-left: 1rem;
}

.about-features {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

.feature-card {
  background: var(--bg-card);
  border: 1px solid rgba(0,180,255,0.1);
  padding: 1.2rem;
  transition: all 0.3s;
}

.feature-card:hover {
  border-color: rgba(0,180,255,0.3);
  box-shadow: 0 0 15px rgba(0,180,255,0.1);
}

.feature-icon { font-size: 1.5rem; margin-bottom: 0.5rem; }

.feature-card h3 {
  font-family: var(--font-ui);
  font-size: 1rem;
  font-weight: 600;
  color: var(--text-bright);
  margin-bottom: 0.3rem;
}

.feature-card p {
  font-size: 0.85rem;
  color: var(--text-muted);
  line-height: 1.4;
}

/* ─── Projects ─── */
.projects-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.5rem;
}

.project-card {
  position: relative;
  background: var(--bg-card);
  border: 1px solid rgba(0,180,255,0.1);
  padding: 1.5rem;
  transition: all 0.3s;
  overflow: hidden;
}

.project-card:hover {
  border-color: var(--cyan);
  box-shadow: 0 0 20px rgba(0,180,255,0.15);
  transform: translateY(-4px);
}

.project-card-glow {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: linear-gradient(90deg, transparent, var(--cyan), transparent);
  opacity: 0;
  transition: opacity 0.3s;
}

.project-card:hover .project-card-glow { opacity: 1; }

.project-icon { font-size: 2rem; margin-bottom: 0.8rem; }

.project-number {
  position: absolute;
  top: 1rem;
  right: 1rem;
  font-family: var(--font-mono);
  font-size: 0.65rem;
  color: var(--text-muted);
  letter-spacing: 0.1em;
}

.project-card h3 {
  font-family: var(--font-ui);
  font-size: 1.1rem;
  font-weight: 600;
  color: var(--text-bright);
  margin-bottom: 0.3rem;
}

.project-tag {
  font-family: var(--font-mono);
  font-size: 0.55rem;
  color: var(--cyan);
  letter-spacing: 0.15em;
  margin-bottom: 0.8rem;
}

.project-card > p {
  font-size: 0.85rem;
  color: var(--text-muted);
  line-height: 1.5;
  margin-bottom: 1rem;
}

.project-tech {
  display: flex;
  flex-wrap: wrap;
  gap: 0.3rem;
  margin-bottom: 1rem;
}

.tech-badge {
  padding: 0.15rem 0.5rem;
  background: rgba(0,180,255,0.08);
  border: 1px solid rgba(0,180,255,0.15);
  font-family: var(--font-mono);
  font-size: 0.55rem;
  color: var(--cyan);
  letter-spacing: 0.05em;
}

.project-stats {
  display: flex;
  gap: 1rem;
  padding-top: 0.8rem;
  border-top: 1px solid rgba(0,180,255,0.1);
  margin-bottom: 1rem;
}

.proj-stat {
  text-align: center;
  flex: 1;
}

.proj-num {
  display: block;
  font-family: var(--font-display);
  font-size: 1.2rem;
  color: var(--cyan-bright);
}

.proj-label {
  font-family: var(--font-mono);
  font-size: 0.5rem;
  color: var(--text-muted);
  letter-spacing: 0.1em;
}

.project-link {
  font-family: var(--font-mono);
  font-size: 0.65rem;
  color: var(--cyan);
  text-decoration: none;
  letter-spacing: 0.1em;
  transition: color 0.3s;
}

.project-link:hover { color: var(--cyan-bright); }

/* ─── Skills ─── */
.skills-grid {
  max-width: 700px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.skill-item { padding: 0.3rem 0; }

.skill-header {
  display: flex;
  justify-content: space-between;
  font-family: var(--font-ui);
  font-size: 0.95rem;
  margin-bottom: 0.3rem;
}

.skill-header span:first-child { color: var(--text-bright); }
.skill-val { font-family: var(--font-mono); color: var(--cyan); font-size: 0.85rem; }

.skill-bar {
  height: 4px;
  background: rgba(0,30,60,0.5);
  border-radius: 2px;
  overflow: hidden;
}

.skill-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--cyan-dim), var(--cyan-bright));
  border-radius: 2px;
  transition: width 1s ease;
}

/* ─── Contact ─── */
.contact-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3rem;
  max-width: 900px;
  margin: 0 auto;
}

.contact-info { display: flex; flex-direction: column; gap: 1.2rem; }

.contact-item {
  display: flex;
  gap: 1rem;
  align-items: flex-start;
}

.contact-icon { font-size: 1.2rem; margin-top: 0.1rem; }

.contact-label {
  display: block;
  font-family: var(--font-mono);
  font-size: 0.6rem;
  color: var(--text-muted);
  letter-spacing: 0.15em;
  margin-bottom: 0.2rem;
}

.contact-value {
  font-family: var(--font-ui);
  font-size: 1rem;
  color: var(--text-bright);
  font-weight: 500;
}

.contact-note {
  margin-top: 1rem;
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: var(--text-muted);
  line-height: 1.5;
}

.contact-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.form-group input,
.form-group textarea {
  width: 100%;
  padding: 0.8rem 1rem;
  background: var(--bg-card);
  border: 1px solid rgba(0,180,255,0.15);
  color: var(--text);
  font-family: var(--font-ui);
  font-size: 0.95rem;
  outline: none;
  transition: border-color 0.3s;
  clip-path: polygon(6px 0, 100% 0, 100% calc(100% - 6px), calc(100% - 6px) 100%, 0 100%, 0 6px);
}

.form-group input:focus,
.form-group textarea:focus {
  border-color: var(--cyan);
}

.contact-btn {
  align-self: flex-start;
  margin-top: 0.5rem;
}

/* ─── Footer ─── */
.footer {
  background: var(--bg-alt);
  padding: 3rem 2rem;
  margin-top: 3rem;
}

.footer-content {
  max-width: 1200px;
  margin: 0 auto;
  text-align: center;
}

.footer-brand {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  margin-bottom: 1rem;
}

.footer-text {
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: var(--text-muted);
  margin-bottom: 1rem;
  letter-spacing: 0.05em;
}

.footer-links {
  display: flex;
  justify-content: center;
  gap: 1.5rem;
  margin-bottom: 1.5rem;
}

.footer-links a {
  font-family: var(--font-mono);
  font-size: 0.65rem;
  color: var(--text-muted);
  text-decoration: none;
  letter-spacing: 0.1em;
  transition: color 0.3s;
}

.footer-links a:hover { color: var(--cyan); }

.footer-copy {
  font-family: var(--font-mono);
  font-size: 0.55rem;
  color: var(--text-muted);
  letter-spacing: 0.1em;
}

.footer-corner {
  position: absolute;
  width: 30px;
  height: 30px;
  border-color: var(--cyan);
  opacity: 0.2;
}

.footer-corner.tl { top: 1rem; left: 1rem; border-top: 2px solid; border-left: 2px solid; }
.footer-corner.tr { top: 1rem; right: 1rem; border-top: 2px solid; border-right: 2px solid; }
.footer-corner.bl { bottom: 1rem; left: 1rem; border-bottom: 2px solid; border-left: 2px solid; }
.footer-corner.br { bottom: 1rem; right: 1rem; border-bottom: 2px solid; border-right: 2px solid; }

/* ─── Responsive ─── */
@media (max-width: 900px) {
  .hero h1 { font-size: 2.5rem; }
  .about-grid { grid-template-columns: 1fr; }
  .about-features { grid-template-columns: 1fr; }
  .projects-grid { grid-template-columns: 1fr; }
  .contact-container { grid-template-columns: 1fr; }
  .nav-links { display: none; }
  .hamburger { display: flex; }
}

@media (max-width: 600px) {
  .hero h1 { font-size: 2rem; }
  .hero-stats { gap: 1.5rem; }
  .stat-num { font-size: 1.8rem; }
}
CSSEOF

# ─── app.js ───
cat > "$PROJECT_DIR/js/app.js" << 'JSEOF'
// ═══════════════════════════════════════════
// STARDANCE PORTFOLIO — JAVASCRIPT
// ═══════════════════════════════════════════

// ─── Particle System ───
const canvas = document.getElementById('particles');
const ctx = canvas.getContext('2d');
let particles = [];
let mouse = { x: 0, y: 0 };

function resizeCanvas() {
  canvas.width = window.innerWidth;
  canvas.height = window.innerHeight;
}

function createParticles() {
  const count = Math.min(100, Math.floor(window.innerWidth / 10));
  particles = [];
  for (let i = 0; i < count; i++) {
    particles.push({
      x: Math.random() * canvas.width,
      y: Math.random() * canvas.height,
      vx: (Math.random() - 0.5) * 0.5,
      vy: (Math.random() - 0.5) * 0.5,
      size: Math.random() * 2 + 0.5,
      opacity: Math.random() * 0.5 + 0.2
    });
  }
}

function drawParticles() {
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  for (const p of particles) {
    p.x += p.vx;
    p.y += p.vy;

    if (p.x < 0) p.x = canvas.width;
    if (p.x > canvas.width) p.x = 0;
    if (p.y < 0) p.y = canvas.height;
    if (p.y > canvas.height) p.y = 0;

    // Mouse interaction
    const dx = p.x - mouse.x;
    const dy = p.y - mouse.y;
    const dist = Math.sqrt(dx * dx + dy * dy);
    if (dist < 150) {
      const force = (150 - dist) / 150;
      p.x += (dx / dist) * force * 2;
      p.y += (dy / dist) * force * 2;
    }

    ctx.beginPath();
    ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(0, 210, 255, ${p.opacity})`;
    ctx.fill();
  }

  // Draw connections
  for (let i = 0; i < particles.length; i++) {
    for (let j = i + 1; j < particles.length; j++) {
      const dx = particles[i].x - particles[j].x;
      const dy = particles[i].y - particles[j].y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      if (dist < 100) {
        ctx.beginPath();
        ctx.moveTo(particles[i].x, particles[i].y);
        ctx.lineTo(particles[j].x, particles[j].y);
        ctx.strokeStyle = `rgba(0, 180, 255, ${0.1 * (1 - dist / 100)})`;
        ctx.lineWidth = 0.5;
        ctx.stroke();
      }
    }
  }

  requestAnimationFrame(drawParticles);
}

window.addEventListener('resize', () => {
  resizeCanvas();
  createParticles();
});

window.addEventListener('mousemove', (e) => {
  mouse.x = e.clientX;
  mouse.y = e.clientY;
});

resizeCanvas();
createParticles();
drawParticles();

// ─── Scroll Animations ───
const observerOptions = {
  threshold: 0.1,
  rootMargin: '0px 0px -50px 0px'
};

const observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('animate-in');
      if (entry.target.classList.contains('skill-item')) {
        const fill = entry.target.querySelector('.skill-fill');
        if (fill) {
          const width = fill.dataset.width;
          fill.style.width = '0%';
          setTimeout(() => { fill.style.width = width + '%'; }, 100);
        }
      }
      if (entry.target.classList.contains('hero-stat')) {
        const num = entry.target.querySelector('.stat-num');
        if (num) {
          const count = parseInt(num.dataset.count);
          animateCounter(num, count);
        }
      }
    }
  });
}, observerOptions);

document.querySelectorAll('.feature-card, .project-card, .skill-item, .stat').forEach(el => {
  observer.observe(el);
});

// ─── Counter Animation ───
function animateCounter(el, target) {
  let current = 0;
  const increment = target / 30;
  const timer = setInterval(() => {
    current += increment;
    if (current >= target) {
      el.textContent = target;
      clearInterval(timer);
    } else {
      el.textContent = Math.floor(current);
    }
  }, 30);
}

// ─── Mobile Nav ───
const hamburger = document.getElementById('hamburger');
let menuOpen = false;

if (hamburger) {
  hamburger.addEventListener('click', () => {
    menuOpen = !menuOpen;
    const links = document.querySelector('.nav-links');
    if (menuOpen) {
      links.style.display = 'flex';
      links.style.flexDirection = 'column';
      links.style.position = 'absolute';
      links.style.top = '60px';
      links.style.right = '1rem';
      links.style.background = 'rgba(2,10,18,0.95)';
      links.style.padding = '1rem';
      links.style.border = '1px solid rgba(0,180,255,0.2)';
      links.style.gap = '1rem';
      links.style.alignItems = 'flex-end';
    } else {
      links.style.display = '';
      links.style.flexDirection = '';
      links.style.position = '';
      links.style.top = '';
      links.style.right = '';
      links.style.background = '';
      links.style.padding = '';
      links.style.border = '';
      links.style.gap = '';
      links.style.alignItems = '';
    }
  });
}

// Close mobile menu on link click
document.querySelectorAll('.nav-link').forEach(link => {
  link.addEventListener('click', () => {
    if (menuOpen) {
      menuOpen = false;
      const links = document.querySelector('.nav-links');
      links.style.display = '';
      links.style.flexDirection = '';
      links.style.position = '';
      links.style.top = '';
      links.style.right = '';
      links.style.background = '';
      links.style.padding = '';
      links.style.border = '';
      links.style.gap = '';
      links.style.alignItems = '';
    }
  });
});

// ─── Contact Form ───
function handleContact(e) {
  e.preventDefault();
  const btn = e.target.querySelector('button');
  btn.textContent = 'SENT ✓';
  btn.style.background = 'rgba(0,255,136,0.2)';
  btn.style.borderColor = 'rgba(0,255,136,0.4)';
  btn.style.color = '#00ff88';
  setTimeout(() => {
    btn.textContent = 'SEND MESSAGE ⟫';
    btn.style.background = '';
    btn.style.borderColor = '';
    btn.style.color = '';
    e.target.reset();
  }, 2500);
  return false;
}

// ─── Nav link active state ───
window.addEventListener('scroll', () => {
  const sections = document.querySelectorAll('section[id]');
  let current = '';
  sections.forEach(section => {
    const top = section.offsetTop - 100;
    if (window.scrollY >= top) {
      current = section.getAttribute('id');
    }
  });
  document.querySelectorAll('.nav-link').forEach(link => {
    link.style.color = '';
    link.style.borderBottomColor = 'transparent';
    if (link.getAttribute('href') === '#' + current) {
      link.style.color = 'var(--cyan)';
      link.style.borderBottomColor = 'var(--cyan)';
    }
  });
});
JSEOF

echo "✅ Portfolio website built at: $PROJECT_DIR/"
echo "   Files created:"
echo "   - $PROJECT_DIR/index.html"
echo "   - $PROJECT_DIR/css/style.css"
echo "   - $PROJECT_DIR/js/app.js"
echo ""
echo "   Open $PROJECT_DIR/index.html in a browser to view."
