// ═══════════════════════════════════════════
// 📝 DEVLOG HELPER - Auto-generate session logs
// ═══════════════════════════════════════════

class DevlogGenerator {
  constructor(db) {
    this.db = db;
  }

  // Generate a devlog entry for the latest session
  generate(projectId) {
    const project = this.db.getProject(projectId);
    if (!project) return null;

    const tasks = this.db.getTasks(projectId);
    const completedTasks = tasks.filter(t => t.status === 'completed');
    const runningTasks = tasks.filter(t => t.status === 'running');
    const failedTasks = tasks.filter(t => t.status === 'failed' || t.status === 'timeout');

    const totalTime = this._estimateTime(tasks);

    const devlog = {
      projectName: project.name,
      projectId: project.id,
      sessionTime: new Date().toISOString(),
      hoursWorked: Math.round(totalTime / 60),
      summary: this._generateSummary(project, tasks, completedTasks, runningTasks, failedTasks),
      highlights: this._generateHighlights(completedTasks),
      screenshots: [],
      nextSteps: this._generateNextSteps(project, tasks),
      status: project.status,
      progress: project.progress
    };

    return devlog;
  }

  _estimateTime(tasks) {
    let totalMinutes = 0;
    for (const task of tasks) {
      if (task.timeLimit) {
        totalMinutes += task.timeLimit;
      } else {
        totalMinutes += 15; // default 15 min per task
      }
    }
    return totalMinutes;
  }

  _generateSummary(project, tasks, completedTasks, runningTasks, failedTasks) {
    const lines = [];

    lines.push(`Project: ${project.name}`);
    lines.push(`Status: ${project.status.toUpperCase()}`);
    lines.push(`Progress: ${project.progress}%`);
    lines.push('');

    if (completedTasks.length > 0) {
      lines.push(`✅ ${completedTasks.length} task(s) completed:`);
      for (const t of completedTasks) {
        lines.push(`  - ${t.name}`);
      }
      lines.push('');
    }

    if (runningTasks.length > 0) {
      lines.push(`▶ ${runningTasks.length} task(s) running:`);
      for (const t of runningTasks) {
        lines.push(`  - ${t.name} (${t.progress}%)`);
      }
      lines.push('');
    }

    if (failedTasks.length > 0) {
      lines.push(`❌ ${failedTasks.length} task(s) failed:`);
      for (const t of failedTasks) {
        lines.push(`  - ${t.name} (${t.status})`);
      }
      lines.push('');
    }

    if (project.description) {
      lines.push(`Goal: ${project.description}`);
    }

    return lines.join('\n');
  }

  _generateHighlights(completedTasks) {
    if (completedTasks.length === 0) return [];

    return completedTasks.map(t => {
      const outputs = t.output.filter(o => o.type === 'success' || o.type === 'stdout');
      const lastOutput = outputs.length > 0 ? outputs[outputs.length - 1].text : '';

      return {
        task: t.name,
        output: lastOutput.substring(0, 200),
        result: 'Completed successfully'
      };
    });
  }

  _generateNextSteps(project, tasks) {
    const pending = tasks.filter(t => t.status === 'pending');
    const todo = [];

    if (pending.length > 0) {
      todo.push(`Continue with ${pending.length} pending task(s):`);
      for (const t of pending) {
        todo.push(`  - ${t.name}`);
      }
    }

    if (project.status === 'completed') {
      todo.push('Project complete! Deploy and submit to Stardance.');
    } else if (project.status === 'failed') {
      todo.push('Review failed tasks and retry or adjust plan.');
    } else if (project.tasks.length === 0) {
      todo.push('Add tasks to begin work on this project.');
    }

    return todo;
  }

  // Format as markdown for easy copy-paste to Stardance
  toMarkdown(devlog) {
    return `# Devlog: ${devlog.projectName}

**Session:** ${new Date(devlog.sessionTime).toLocaleString()}
**Hours:** ${devlog.hoursWorked} hrs
**Progress:** ${devlog.progress}%
**Status:** ${devlog.status.toUpperCase()}

---

${devlog.summary}

---

## Key Accomplishments

${devlog.highlights.map(h => `- **${h.task}**: ${h.result}`).join('\n') || 'No highlights yet.'}

---

## Next Steps

${devlog.nextSteps.join('\n')}

---

*Generated by Stardance Remote Control*
`;
  }

  // Generate a quick screenshot description (since we can't take actual screenshots)
  generateScreenshotDesc(devlog) {
    return {
      description: `Dashboard view of ${devlog.projectName} at ${devlog.progress}% completion`,
      whatToCapture: 'The project dashboard showing task progress, status badges, and completed tasks list',
      tip: 'Use browser devtools screenshot or screen capture tool'
    };
  }
}

module.exports = DevlogGenerator;
